Fix publish job
The name of the action was wrong, leading to:

    Error: Unable to resolve action actions/download-artifacts, repository not found

The publish job also started before the build job. Fixed by adding the
missing dependency.